steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/in-class-activity-424123/backappdb:latest', './backend']
    dir: 'backend'

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/in-class-activity-424123/backappdb:latest']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/in-class-activity-424123/frontapp:latest', './frontend']
    dir: 'frontend'

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/in-class-activity-424123/frontapp:latest']

  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'apply'
      - '-f'
      - './backend/deployment.yaml'
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
      - 'CLOUDSDK_CONTAINER_CLUSTER=my-cluster2'

  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'apply'
      - '-f'
      - './frontend/deployment.yaml'
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
      - 'CLOUDSDK_CONTAINER_CLUSTER=my-cluster2'

options:
  logging:
    - CLOUD_LOGGING_ONLY  # Use only Cloud Logging for logging

build:
  service_account: singhsimranjeet147@gmail.com  # Replace with your service account email
